# Generated by Django 4.2.2 on 2023-07-23 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=20)),
                ('EMail', models.EmailField(max_length=254)),
                ('Querry', models.CharField(max_length=500)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
