# Generated by Django 4.2.2 on 2023-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminID', models.CharField(max_length=20)),
                ('AdminKey', models.IntegerField()),
                ('AdminPassword', models.CharField(max_length=20)),
            ],
        ),
    ]
